# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            form_login:
                provider: fos_userbundle
                csrf_provider: security.csrf.token_manager

            logout:       true
            anonymous:    true
            
    encoders:
        #Symfony\Component\Security\Core\User\User: plaintext  #for in_memory provider
        FOS\UserBundle\Model\UserInterface: bcrypt
        
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username
            
    access_control:
      - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
      - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
      - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
      - { path: ^/admin, role: ROLE_ADMIN }
      
      
      
# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
          pattern:    ^/
          fr3d_ldap:  ~
          form_login:
              always_use_default_target_path: true
              default_target_path: /profile
          logout:     true
          anonymous:  true
    
    # Preserve plain text password in token for refresh the user.
    # Analyze the security considerations before turn off this setting.
    erase_credentials: false        
            
    encoders:
        #Symfony\Component\Security\Core\User\User: plaintext  #for in_memory provider
        AppBundle\Entity\User: plaintext
        
    role_hierarchy:
        ROLE_UNCONFIRMED: ~
        ROLE_USER:        ROLE_UNCONFIRMED
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        chain_provider:
            chain:
                providers: [fos_userbundle, fr3d_ldapbundle]

        fr3d_ldapbundle:
            id: fr3d_ldap.security.user.provider

        fos_userbundle:
            id: fos_user.user_provider.username
            
    access_control:
      - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
      - { path: ^/register, role: ROLE_SUPER_ADMIN } #login through LDAP, should not need to register
      - { path: ^/admin, role: ROLE_ADMIN }

