<?php

namespace AppBundle\Entity;

/**
 * StaffDepartmentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StaffDepartmentRepository extends \Doctrine\ORM\EntityRepository
{
  /**
   * Show all departments
   */
  public function listDepartments(){
    
  }
}
