<?php

namespace AppBundle\Entity;

/**
 * FunctionalAreaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StaffAreaRepository extends \Doctrine\ORM\EntityRepository
{

}

