<?php

namespace AppBundle\Entity;

/**
 * StaffDepartmentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
  /**
   * @param String $type  null shows all users, active shows active, inactive shows inactive
   * @return Array $users   an array of user objects
   */
  public function listUsers($type = null){
    $em = $this->getEntityManager();
    
    switch($type){
      case 'active':
        $users = $em->createQuery(
            'SELECT u FROM AppBundle:User u WHERE u.isActive = :isActive ORDER BY u.username ASC'
        )->setParameter('isActive', 1)->getResult();
        break;
      case 'inactive':
        $users = $em->createQuery(
            'SELECT u FROM AppBundle:User u WHERE u.isActive = :isActive ORDER BY u.username ASC'
        )->setParameter('isActive', 0)->getResult();
        break;
      default:
        $users = $em->createQuery(
            'SELECT u FROM AppBundle:User u ORDER BY u.username ASC'
        )->getResult();
    }
    return $users;
  }
}

